function(dcp_add_test name)
  add_executable(${name} ${name}.c)
  target_link_libraries(${name} PRIVATE DECIPHON::deciphon)
  target_link_libraries(${name} PRIVATE IMM::imm)
  target_compile_options(${name} PRIVATE ${WARNING_FLAGS})
  target_include_directories(${name} PRIVATE ${CMAKE_SOURCE_DIR})
  add_test(NAME ${name} COMMAND ${name})
endfunction()

function(dcp_download_assets dest)
  set(url https://s3.danilohorta.me/blx)
  file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/MANIFEST lines)
  while(lines)
    list(POP_FRONT lines line)
    string(REPLACE " " ";" args ${line})
    list(POP_FRONT args cid)
    list(POP_FRONT args name)
    file(DOWNLOAD ${url}/${cid} ${dest}/${name} EXPECTED_HASH SHA256=${cid})
  endwhile()
endfunction()
