function(deciphon_add_test name tmpdir )
  add_executable(${name} ${name}.c)
  target_link_libraries(${name} PRIVATE DECIPHON::deciphon)
  target_link_libraries(${name} PRIVATE ${ARGN})
  target_compile_definitions(${name} PRIVATE TMPDIR="${tmpdir}")
  add_test(NAME test_${name} COMMAND ${name})
endfunction()

function(deciphon_file_hash file ret)
  file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/manifest lines)
  while(lines)
    list(POP_FRONT lines line)
    if(line MATCHES "^.* ${file}$")
      string(REPLACE " " ";" line ${line})
      list(GET line 0 hash)
      set(${ret}
          "${hash}"
          PARENT_SCOPE)
      break()
    endif()
  endwhile()
endfunction()

function(deciphon_download file)
  deciphon_file_hash(${file} hash)
  message(STATUS "FOUND: ${hash}")
  set(url "https://pub.danilohorta.me/deciphon")
  message(STATUS "${url}/${file} EXPECTED_HASH SHA256=${hash}")
  file(DOWNLOAD ${url}/${file} ${file} EXPECTED_HASH SHA256=${hash})
endfunction()
