#!/bin/bash

PROGRAM=$1
HMM=$2

# shellcheck disable=SC1091
source "tools/unittest"

unittest_setup "$PROGRAM" tools/dotenv_get .env "$HMM"
unittest_exec "$PROGRAM"

HOST=$(tools/dotenv_get .env DCP_API_HOST)
PORT=$(tools/dotenv_get .env DCP_API_PORT)
KEY=$(tools/dotenv_get .env DCP_API_KEY)

unittest_sendnl "connect http://$HOST:$PORT $KEY"
unittest_sendnl "online"
unittest_sendnl "wipe"
unittest_sendnl "hmm_up $HMM"
unittest_sendnl "job_next_pend"
unittest_sendnl "job_set_state 1 run"
unittest_sendnl "job_inc_progress 1 10"
unittest_sendnl "job_set_state 1 fail error-message"
unittest_stop

{
    echo "OK"
    echo "YES"
    echo "OK"
    echo "OK"
    echo '{"id":1,"type":1,"state":"pend","progress":0,"error":"","submission":XXX,"exec_started":0,"exec_ended":0}'
    echo "OK"
    echo "OK"
    echo "OK"
} >desired

sed 's/"submission":[0-9]*/"submission":XXX/g' <stdout >stdout.2 && mv stdout.2 stdout

diff stdout desired
