#!/bin/bash

PROGRAM=$1
HMM=$2

# shellcheck disable=SC1091
source "tools/unittest"

unittest_setup "$PROGRAM" tools/dotenv_get .env "$HMM"
unittest_exec "$PROGRAM"

HOST=$(tools/dotenv_get .env DCP_API_HOST)
PORT=$(tools/dotenv_get .env DCP_API_PORT)
KEY=$(tools/dotenv_get .env DCP_API_KEY)

unittest_sendnl "CONNECT http://$HOST:$PORT $KEY"
unittest_sendnl "ONLINE"
unittest_sendnl "WIPE"
unittest_sendnl "HMM_UP $HMM"
unittest_stop

{
    echo "OK"
    echo "YES"
    echo "OK"
    echo "OK"
} >desired

diff stdout desired
