#!/bin/bash

PROGRAM=$1
HMM=$2
HMM_FILENAME=$(basename "$HMM")

# shellcheck disable=SC1091
source "tools/unittest"

unittest_setup "$PROGRAM" tools/dotenv_get .env "$HMM"
unittest_exec "$PROGRAM"

HOST=$(tools/dotenv_get .env DCP_API_HOST)
PORT=$(tools/dotenv_get .env DCP_API_PORT)
KEY=$(tools/dotenv_get .env DCP_API_KEY)

unittest_sendnl "connect http://$HOST:$PORT $KEY"
unittest_sendnl "online"
unittest_sendnl "wipe"
unittest_sendnl "hmm_up $HMM"
unittest_sendnl "hmm_get_by_id 1"
unittest_sendnl "hmm_get_by_xxh3 -7843725841264658444"
unittest_sendnl "hmm_get_by_filename $HMM_FILENAME"
unittest_sendnl "hmm_dl -7843725841264658444 output.hmm"
unittest_stop

{
    echo "OK"
    echo "YES"
    echo "OK"
    echo "OK"
    echo '{"id":1,"xxh3":-7843725841264658444,"filename":"PF02545.hmm","job_id":1}'
    echo '{"id":1,"xxh3":-7843725841264658444,"filename":"PF02545.hmm","job_id":1}'
    echo '{"id":1,"xxh3":-7843725841264658444,"filename":"PF02545.hmm","job_id":1}'
    echo "OK"
} >desired

diff stdout desired
