#!/bin/bash

PROGRAM=$1
HMM=$2
DB=$3
CONSENSUS=$4
PRODS_FILE=$5

# shellcheck disable=SC1091
source "tools/unittest"

unittest_setup "$PROGRAM" tools/dotenv_get .env "$HMM" "$CONSENSUS" "$PRODS_FILE"
unittest_exec "$PROGRAM"

HOST=$(tools/dotenv_get .env DCP_API_HOST)
PORT=$(tools/dotenv_get .env DCP_API_PORT)
KEY=$(tools/dotenv_get .env DCP_API_KEY)

unittest_sendnl "CONNECT http://$HOST:$PORT $KEY"
unittest_sendnl "ONLINE"
unittest_sendnl "WIPE"
unittest_sendnl "HMM_UP $HMM"
unittest_sendnl "JOB_SET_STATE 1 run"
unittest_sendnl "JOB_SET_STATE 1 done"
unittest_sendnl "DB_UP $DB"
unittest_stop

{
    echo "OK"
    echo "YES"
    echo "OK"
    echo "OK"
    echo "OK"
    echo "OK"
    echo "OK"
} >desired

diff stdout desired
