#!/bin/bash

PROGRAM=$1
HMM=$2
DB=$3
DB_FILENAME=$(basename "$DB")

# shellcheck disable=SC1091
source "tools/unittest"

unittest_setup "$PROGRAM" tools/dotenv_get .env "$DB"
unittest_exec "$PROGRAM"

HOST=$(tools/dotenv_get .env DCP_API_HOST)
PORT=$(tools/dotenv_get .env DCP_API_PORT)
KEY=$(tools/dotenv_get .env DCP_API_KEY)

unittest_sendnl "setup http://$HOST:$PORT $KEY"
unittest_sendnl "online"
unittest_sendnl "wipe"
unittest_sendnl "hmm_up $HMM"
unittest_sendnl "db_up $DB"
unittest_sendnl "db_get_by_id 1"
unittest_sendnl "db_get_by_xxh3 -7843725841264658444"
unittest_sendnl "db_get_by_filename $DB_FILENAME"
# unittest_sendnl "DB_DL -7843725841264658444 output.dcp"
unittest_stop

{
    echo "OK"
    echo "YES"
    echo "OK"
    echo "OK"
    echo "OK"
    echo '{"id":1,"xxh3":-7843725841264658444,"filename":"PF02545.dcp","hmm_id":1}'
    echo '{"id":1,"xxh3":-7843725841264658444,"filename":"PF02545.dcp","hmm_id":1}'
    echo '{"id":1,"xxh3":-7843725841264658444,"filename":"PF02545.dcp","hmm_id":1}'
} >desired

diff stdout desired
