#!/bin/bash

unittest_origin=$PWD
cd "$(mktemp -d)" || exit 1
unittest_pid=

function unittest_exec() {
    program=$1
    mkfifo stdin
    exec "$unittest_origin/$program" <stdin >stdout 2>stderr &
    unittest_pid=$!
}

function unittest_stop() {
    sleep 0.5
    { kill -15 "$unittest_pid" && wait "$unittest_pid"; } 2>/dev/null
    sleep 0.5
}

function unittest_sendnl() {
    echo "$1" >>stdin
}
