#!/bin/bash

set -e
export DEBUG=1
echo "vamos la"

bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s horta/hope
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s horta/logaddexp
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s horta/elapsed
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s horta/almosthere
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s EBI-Metagenomics/c-containers
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s EBI-Metagenomics/log
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s EBI-Metagenomics/hmmer-reader
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s EBI-Metagenomics/fasta
bash -c "$(curl -H 'Cache-Control: no-cache' -fsSL https://git.io/JerYI)" -s EBI-Metagenomics/imm
