#!/bin/bash

bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s horta/hope || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s horta/logaddexp || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/c-containers || exit 1

bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s horta/elapsed || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/log || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/hmmer-reader || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/fasta || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/imm || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/tabulate || exit 1
bash -c "$(curl -fsSL https://bit.ly/3Kv06KA)" -s EBI-Metagenomics/gff || exit 1
