#ifndef DCP_LIMITS_H
#define DCP_LIMITS_H

#define DCP_ABC_NAME_SIZE 16
#define DCP_DB_NAME_SIZE 64
#define DCP_ERROR_SIZE 256
#define DCP_MATCH_DATA_SIZE (2 * 16384)
#define DCP_MODEL_SIZE 16
#define DCP_FILENAME_SIZE 128
#define DCP_PATH_SIZE 4096
#define DCP_PROF_NAME_SIZE 256
#define DCP_SEQ_NAME_SIZE 256
#define DCP_SEQ_SIZE 16384
#define DCP_STATE_SIZE 5
#define DCP_VERSION_SIZE 16

#endif
