#ifndef DCP_PROTEIN_ID_H
#define DCP_PROTEIN_ID_H

#include "profile_types.h"

#define DCP_PROTEIN_ID_MATCH (0U << (DCP_PROFILE_BITS_ID - 2))
#define DCP_PROTEIN_ID_INSERT (1U << (DCP_PROFILE_BITS_ID - 2))
#define DCP_PROTEIN_ID_DELETE (2U << (DCP_PROFILE_BITS_ID - 2))
#define DCP_PROTEIN_ID_EXT (3U << (DCP_PROFILE_BITS_ID - 2))
#define DCP_PROTEIN_ID_R (DCP_PROTEIN_ID_EXT | 0U)
#define DCP_PROTEIN_ID_S (DCP_PROTEIN_ID_EXT | 1U)
#define DCP_PROTEIN_ID_N (DCP_PROTEIN_ID_EXT | 2U)
#define DCP_PROTEIN_ID_B (DCP_PROTEIN_ID_EXT | 3U)
#define DCP_PROTEIN_ID_E (DCP_PROTEIN_ID_EXT | 4U)
#define DCP_PROTEIN_ID_J (DCP_PROTEIN_ID_EXT | 5U)
#define DCP_PROTEIN_ID_C (DCP_PROTEIN_ID_EXT | 6U)
#define DCP_PROTEIN_ID_T (DCP_PROTEIN_ID_EXT | 7U)

#endif
