#include "sched_schema.h"
#include "stringify.h"
#include <assert.h>

#define STATE_LEN STRINGIFY(SCHED_SCHEMA_STATE_LEN)
#define SHORT_LEN STRINGIFY(SCHED_SCHEMA_SHORT_LEN)
#define ERROR_LEN STRINGIFY(SCHED_SCHEMA_ERROR_LEN)
#define NAME_LEN STRINGIFY(SCHED_SCHEMA_NAME_LEN)
#define DATA_LEN STRINGIFY(SCHED_SCHEMA_DATA_LEN)

#define PATH_LENGTH 4095
static_assert(PATH_SIZE - 1 == PATH_LENGTH, "Path length string");
#define PATH_LEN STRINGIFY(PATH_LENGTH)

// clang-format off
unsigned char sched_schema[] =
"PRAGMA foreign_keys = off;                                                    "
"BEGIN TRANSACTION;                                                            "
"                                                                              "
"CREATE TABLE job (                                                            "
"    id            INTEGER     PRIMARY KEY AUTOINCREMENT,                      "
"                              UNIQUE                                          "
"                              NOT NULL,                                       "
"    db_id         INTEGER     REFERENCES db (id)                              "
"                              NOT NULL,                                       "
"    multi_hits    BOOLEAN     NOT NULL,                                       "
"    hmmer3_compat BOOLEAN     NOT NULL,                                       "
"    state         VARCHAR(" STATE_LEN ")                                      "
"                              CHECK(state IN ('pend', 'run', 'done', 'fail')) "
"                              NOT NULL                                        "
"                              DEFAULT ('pend'),                               "
"    error         VARCHAR(" ERROR_LEN ")                                      "
"                              NOT NULL                                        "
"                              DEFAULT (''),                                   "
"    submission    INTEGER     NOT NULL                                        "
"                              DEFAULT (0),                                    "
"    exec_started  INTEGER     NOT NULL                                        "
"                              DEFAULT (0),                                    "
"    exec_ended    INTEGER     NOT NULL                                        "
"                              DEFAULT (0)                                     "
");                                                                            "
"                                                                              "
"                                                                              "
"CREATE TABLE seq (                                                            "
"    id     INTEGER PRIMARY KEY AUTOINCREMENT                                  "
"                   UNIQUE                                                     "
"                   NOT NULL,                                                  "
"    job_id INTEGER REFERENCES job (id)                                        "
"                   NOT NULL,                                                  "
"    name VARCHAR(" NAME_LEN ") NOT NULL,                                      "
"    data VARCHAR(16383) NOT NULL                                              "
");                                                                            "
"                                                                              "
"                                                                              "
"CREATE TABLE prod (                                                           "
"    id          INTEGER PRIMARY KEY AUTOINCREMENT                             "
"                        UNIQUE                                                "
"                        NOT NULL,                                             "
"    job_id      INTEGER REFERENCES job (id)                                   "
"                        NOT NULL,                                             "
"    seq_id      INTEGER REFERENCES seq (id)                                   "
"                        NOT NULL,                                             "
"    match_id    INTEGER NOT NULL,                                             "
"    prof_name   VARCHAR(" NAME_LEN ") NOT NULL,                               "
"    start_pos   INTEGER NOT NULL,                                             "
"    end_pos     INTEGER NOT NULL,                                             "
"    abc_id      VARCHAR(" SHORT_LEN ") NOT NULL,                              "
"    loglik      VARCHAR(" SHORT_LEN ") NOT NULL,                              "
"    null_loglik VARCHAR(" SHORT_LEN ") NOT NULL,                              "
"    model       VARCHAR(" SHORT_LEN ") NOT NULL,                              "
"    version     VARCHAR(" SHORT_LEN ") NOT NULL,                              "
"    match_data  VARCHAR(16383) NOT NULL                                       "
");                                                                            "
"                                                                              "
"                                                                              "
"CREATE TABLE db (                                                             "
"    id       INTEGER PRIMARY KEY AUTOINCREMENT                                "
"                     UNIQUE                                                   "
"                     NOT NULL,                                                "
"    name     VARCHAR(" NAME_LEN ")                                            "
"                     NOT NULL,                                                "
"    filepath VARCHAR(" PATH_LEN ")                                            "
"                     UNIQUE                                                   "
"                     NOT NULL                                                 "
");                                                                            "
"                                                                              "
"COMMIT TRANSACTION;                                                           "
"PRAGMA foreign_keys = on;                                                     "
;
// clang-format on
