#ifndef SCHED_LIMITS_H
#define SCHED_LIMITS_H

#include "dcp/limits.h"
#include "xlimits.h"

#define SCHED_STATE_SIZE DCP_STATE_SIZE
#define SCHED_SHORT_SIZE DCP_ABC_NAME_SIZE
#define SCHED_ERROR_SIZE DCP_ERROR_SIZE
#define SCHED_NAME_SIZE DCP_PROF_NAME_SIZE
#define SCHED_DATA_SIZE DCP_SEQ_SIZE

#endif
