#!/bin/bash

if type realpath >/dev/null 2>&1; then
    realpath "$1"
elif type readlink >/dev/null 2>&1; then
    readlink -e "$1"
else
    echo "$(
        cd "$(dirname -- "$1")" >/dev/null || exit 1
        pwd -P
    )/$(basename -- "$1")"
fi
