#!/bin/bash

# Stop on first error
set -e

status=$(curl -I -X GET --no-progress-meter http://127.0.0.1:49329 2>&1 | head -n1)
http_code=$(echo "$status" | cut -d' ' -f2)
if [ "$http_code" == "200" ]; then
    exit 0
fi

echo "Failed to reach deciphon api: $status" >&2
exit 1
