#!/bin/bash

unittest_pid=

function unittest_setup() {
    tmpdir=$(mktemp -d)

    for file in "$@"; do
        if [[ "$file" = /* ]]; then
            dst=$tmpdir
        else
            dst="$tmpdir"/"$(dirname "$file")"
            mkdir -p "$dst"
        fi
        cp "$file" "$dst"
    done

    cd "$tmpdir" || exit 1
    echo "Working directory: $PWD"
}

function unittest_exec() {
    program=$1
    mkfifo stdin
    exec "$program" <stdin >stdout 2>stderr &
    unittest_pid=$!
}

function unittest_stop() {
    sleep 0.5
    { kill -15 "$unittest_pid" && wait "$unittest_pid"; } 2>/dev/null
    sleep 0.5
}

function unittest_sendnl() {
    echo "$1" >>stdin
}
